BVS/Models/Entity/Parceria/InicioParceria.cs
using BVS.Models.Entity.CompradorAssociado;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BVS.Models.Entity.Parceria
{
    public class InicioParceria : ACadastroBoi
    {

        public Guid IdComprador { get; private set; }
        public Comprador? Comprador { get; private set; }
        public Guid IdAssociado { get; private set; }
        public Associado? Associado { get; private set; }

        [Display(Name = "Inicio da Paceria")]        
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date, ErrorMessage ="Data em formato inválido")]
        public DateTime DataInicioParceria { get; private set; }

        public int Quantidade { get; private set; }        
        [DisplayName("Origem")]
        public string? Origem { get; private set; }
        //[DisplayName("Porcentagem do Mês")]
        //public decimal PorcentoMes { get; private set; }
        [DisplayName("Valor")]
        [DisplayFormat(DataFormatString = "{0:C}", ApplyFormatInEditMode = true)]
        public decimal Valor { get; private set; }
        public string Lote { get; private set; }
        
        public ICollection<AlteracaoSaida> AlteracaoSaidas { get; set; }
        public InicioParceria(Guid boiId, string lote, int quantidade, decimal pesoBruto, decimal valor, string? origem, decimal arroba,
            decimal rendimentoCarcaca,DateTime dataInicioParceria,Guid idComprador, Guid idAssociado, Classificacao classificacao, 
            CompraVenda compraVenda)
        {
            BoiId = boiId;
            Lote = lote;
            Quantidade = quantidade;
            PesoBruto = pesoBruto;
            Valor = valor;
            Origem = origem;
            //PorcentoMes = porcentoMes;            
            Arroba = arroba;
            RendimentoCarcaca = rendimentoCarcaca;
            DataInicioParceria = DateTime.Now;
            IdComprador = idComprador;
            IdAssociado = idAssociado;
            Classificacao = classificacao;
            CompraVenda = compraVenda;
        }

        public InicioParceria(string lote, int quantidade, decimal pesoBruto, decimal valor, string origem, decimal arroba, decimal rendimentoCarcaca, DateTime dataInicioParceria,Guid idComprador, 
            Guid idAssociado,Classificacao classificacao, CompraVenda compraVenda)
            : this(default, lote, quantidade, pesoBruto, valor, origem, arroba, rendimentoCarcaca, dataInicioParceria, idComprador, idAssociado,classificacao, compraVenda)
        {
        }
        public InicioParceria()
        {
        }        
    }
}

BVS/Controllers/AlteracaoSaidasController.cs
using BVS.Models.Entity.ContextBVS;
using BVS.Models.Entity.Parceria;
using BVS.Models.Interface.IServiceBase;
using BVS.Models.Request;
using BVS.Models.Request.Atualizar;
using BVS.Models.Response;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BVS.Controllers
{
    //[ApiVersion("1.0")]
    public class AlteracaoSaidasController : Controller
    {
        private IServiceAlteracaoSaida _saidaService;
        private BVSContext _context;

        public AlteracaoSaidasController(IServiceAlteracaoSaida saidaService, BVSContext context)
        {
            _saidaService = saidaService;
            _context = context;
        }

        //[ClaimsAuthorize(ClaimTypes.AlteracaoSaida, "Ler")]
        [HttpGet]
        public async Task<ActionResult<IEnumerable<AlteracaoSaidaResponse>>> ObterTodos()
        {
            var saidas = await _saidaService.ObterTodosAsync();
            
            return View(saidas);
        }
        //[ClaimsAuthorize(ClaimTypes.AlteracaoSaida, "Ler")]
        [HttpGet]
        public async Task<ActionResult<AlteracaoSaidaResponse>> ObterPorId(Guid id)
        {//AlteracaoSaidaResponse
            var saida = await _saidaService.ObterPorIdAsync(id);                        
            if (saida is null)
                return NotFound("Dados inválidos, verifique e tente novamente.");

            //var saidasResponse = AlteracaoSaidaResponse.ConverteParaResponse(saida);
            return View(saida);
        }
        public async Task<IActionResult> Inserir(Guid id)
        {
            ViewBag.selectParcerias = from iParc in _context.InicioParcerias
                                      where iParc.BoiId == id
                                      select iParc;

            var iniParceria = (from ini in _context.InicioParcerias
                      select new SelectListItem()
                      {
                          Text = ini.Lote,
                          Value = ini.BoiId.ToString()
                      }).ToList();
            iniParceria.Insert(0, new SelectListItem()
            {
                Text = "---Selecione---",
                Value = string.Empty
            });
            ViewBag.selectParceria = iniParceria;
            var cp = (from comp in _context.Compradores
                      select new SelectListItem()
                      {
                          Text = comp.Nome,
                          Value = comp.CadastroId.ToString()
                      }).ToList();
            cp.Insert(0, new SelectListItem()
            {
                Text = "---Selecione---",
                Value = string.Empty
            });
            ViewBag.selectComprador = cp;

            var asp = (from assoc in _context.Associados
                       select new SelectListItem()
                       {
                           Text = assoc.Nome,
                           Value = assoc.CadastroId.ToString()
                       }).ToList();
            asp.Insert(0, new SelectListItem()
            {
                Text = "---Selecione---",
                Value = string.Empty
            });
            ViewBag.selectAssociado = asp;

            var classf = Enum.GetValues(typeof(Classificacao))
             .Cast<Classificacao>()
             .Select(v => new SelectListItem
             {
                 Text = v.ToString(),
                 Value = ((int)v).ToString(),
             }).ToList();
            classf.Insert(0, new SelectListItem()
            {
                Text = "---Selecionar---",
                Value = string.Empty.ToString(),
            });
            ViewData["Classificacao"] = classf;

            var compraV = Enum.GetValues(typeof(CompraVenda))
                .Cast<CompraVenda>()
                .Select(c => new SelectListItem
                {
                    Text = c.ToString(),
                    Value = ((int)c).ToString()
                }).ToList();
            compraV.Insert(0, new SelectListItem()
            {
                Text = "---Selecionar---",
                Value = string.Empty.ToString(),
            });
            ViewData["CompraVenda"] = compraV;
            
            return View();
        }
        //[ClaimsAuthorizeAttribute(ClaimTypes.AlteracaoSaida, "Inserir")]
        [HttpPost]
        public async Task<ActionResult<Guid>> Inserir(InsercaoAlteracaoSaidaRequest saidaRequest)
        {
            var saida = InsercaoAlteracaoSaidaRequest.ConverterParaEntidade(saidaRequest);
             await _saidaService.AdicionarAsync(saida);
            return RedirectToAction("ObterTodos", "InicioParcerias");
        }
        public async Task<IActionResult> Atualizar(Guid id)
        {
            ViewBag.selectParcerias = from iParc in _context.InicioParcerias
                                      where iParc.BoiId == id
                                      select iParc;

            var iniParceria = (from ini in _context.InicioParcerias
                               select new SelectListItem()
                               {
                                   Text = ini.Lote,
                                   Value = ini.BoiId.ToString()
                               }).ToList();
            iniParceria.Insert(0, new SelectListItem()
            {
                Text = "---Selecione---",
                Value = string.Empty
            });
            ViewBag.selectParceria = iniParceria;
            var cp = (from comp in _context.Compradores
                      select new SelectListItem()
                      {
                          Text = comp.Nome,
                          Value = comp.CadastroId.ToString()
                      }).ToList();
            cp.Insert(0, new SelectListItem()
            {
                Text = "---Selecione---",
                Value = string.Empty
            });
            ViewBag.selectComprador = cp;

            var asp = (from assoc in _context.Associados
                       select new SelectListItem()
                       {
                           Text = assoc.Nome,
                           Value = assoc.CadastroId.ToString()
                       }).ToList();
            asp.Insert(0, new SelectListItem()
            {
                Text = "---Selecione---",
                Value = string.Empty
            });
            ViewBag.selectAssociado = asp;

            var classf = Enum.GetValues(typeof(Classificacao))
             .Cast<Classificacao>()
             .Select(v => new SelectListItem
             {
                 Text = v.ToString(),
                 Value = ((int)v).ToString(),
             }).ToList();
            classf.Insert(0, new SelectListItem()
            {
                Text = "---Selecionar---",
                Value = string.Empty.ToString(),
            });
            ViewData["Classificacao"] = classf;

            var compraV = Enum.GetValues(typeof(CompraVenda))
                .Cast<CompraVenda>()
                .Select(c => new SelectListItem
                {
                    Text = c.ToString(),
                    Value = ((int)c).ToString()
                }).ToList();
            compraV.Insert(0, new SelectListItem()
            {
                Text = "---Selecionar---",
                Value = string.Empty.ToString(),
            });
            ViewData["CompraVenda"] = compraV;
            var saida = await _saidaService.ObterPorIdAsync(id);
            return View(saida);
        }
        //[ClaimsAuthorizeAttribute(ClaimTypes.AlteracaoSaida, "Atualizar")]
        [HttpPost]
        public async Task<ActionResult> Atualizar(AtualizarAlteracaoSaidaRequest saidaRequest)
        {
            var saida = AtualizarAlteracaoSaidaRequest.ConverterParaEntidade(saidaRequest);
            await _saidaService.AtualizarAsync(saida);
            return RedirectToAction("ObterTodos");
        }
        //[ClaimsAuthorizeAttribute(ClaimTypes.AlteracaoSaida, "Excluir")]
        
        public async Task<ActionResult> Excluir(Guid id)
        {
            await _saidaService.RemoverPorIdAsync(id);
            return RedirectToAction("ObterTodos");
        }
    }
}

BVS/Controllers/InicioParceriasController.cs
using BVS.Models.Entity.ContextBVS;
using BVS.Models.Entity.Parceria;
using BVS.Models.Interface.IServiceBase;
using BVS.Models.Request;
using BVS.Models.Request.Atualizar;
using BVS.Models.Response;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BVS.Controllers
{
    //[ApiVersion("1.0")]
    public class InicioParceriasController : Controller
    {
        private IServiceInicioParceria _parceriaService;
        private BVSContext _context;
        public InicioParceriasController(IServiceInicioParceria parceriaService, BVSContext context)
        {
            _parceriaService = parceriaService;
            _context = context;
        }

        //[ClaimsAuthorize(ClaimTypes.InicioParceria, "Ler")]
        [HttpGet]
        public async Task<ActionResult<IEnumerable<InicioParceriaResponse>>> ObterTodos()
        {
            var parcerias = await _parceriaService.ObterTodosAsync();
            
            return View(parcerias);
        }
        //[ClaimsAuthorize(ClaimTypes.InicioParceria, "Ler")]
        [HttpGet]
        public async Task<ActionResult<InicioParceriaResponse>> ObterPorId(Guid id)
        {
            var parcerias = await _parceriaService.ObterPorIdAsync(id);

            if (parcerias is null)
                return NotFound();

            //var parceriasResponse = InicioParceriaResponse.ConverteParaResponse(parcerias);
            return View(parcerias);
        }
        public async Task<IActionResult> Inserir(Guid id)
        {
            var cp = (from comp in _context.Compradores
                      select new SelectListItem()
                      {
                          Text = comp.Nome,
                          Value = comp.CadastroId.ToString()
                      }).ToList();
            cp.Insert(0, new SelectListItem()
            {
                Text = "---Selecione---",
                Value = string.Empty
            });
            ViewBag.selectComprador = cp;

            var asp = (from assoc in _context.Associados
                       select new SelectListItem()
                       {
                           Text = assoc.Nome,
                           Value = assoc.CadastroId.ToString()
                       }).ToList();
            asp.Insert(0, new SelectListItem()
            {
                Text = "---Selecione---",
                Value = string.Empty
            });
            ViewBag.selectAssociado = asp;

            var classf = Enum.GetValues(typeof(Classificacao))
             .Cast<Classificacao>()
             .Select(v => new SelectListItem
             {
                 Text = v.ToString(),
                 Value = ((int)v).ToString(),
             }).ToList();
            classf.Insert(0, new SelectListItem()
            {
                Text = "---Selecionar---",
                Value = string.Empty.ToString(),
            });
            ViewData["Classificacao"] = classf;

            var compraV = Enum.GetValues(typeof(CompraVenda))
                .Cast<CompraVenda>()
                .Select(c => new SelectListItem
                {
                    Text = c.ToString(),
                    Value = ((int)c).ToString()
                }).ToList();
            compraV.Insert(0, new SelectListItem()
            {
                Text = "---Selecionar---",
                Value = string.Empty.ToString(),
            });
            ViewData["CompraVenda"] = compraV;
            
            return View();
        }
        //[ClaimsAuthorizeAttribute(ClaimTypes.InicioParceria, "Inserir")]
        [HttpPost]
        public async Task<ActionResult<Guid>> Inserir(InsercaoInicioParceriaRequest insercaoparceria)
        {
            var parceria = InsercaoInicioParceriaRequest.ConverterParaEntidade(insercaoparceria);            
            await _parceriaService.AdicionarAsync(parceria);            
            return RedirectToAction("ObterTodos");
        }
        public async Task<IActionResult> Atualizar(Guid id)
        {
            var cp = (from comp in _context.Compradores
                      select new SelectListItem()
                      {
                          Text = comp.Nome,
                          Value = comp.CadastroId.ToString()
                      }).ToList();
            cp.Insert(0, new SelectListItem()
            {
                Text = "---Selecione---",
                Value = string.Empty
            });
            ViewBag.selectComprador = cp;
            var asp = (from assoc in _context.Associados
                       select new SelectListItem()
                       {
                           Text = assoc.Nome,
                           Value = assoc.CadastroId.ToString()
                       }).ToList();
            asp.Insert(0, new SelectListItem()
            {
                Text = "---Selecione---",
                Value = string.Empty
            });
            ViewBag.selectAssociado = asp;

            var classf = Enum.GetValues(typeof(Classificacao))
             .Cast<Classificacao>()
             .Select(v => new SelectListItem
             {
                 Text = v.ToString(),
                 Value = ((int)v).ToString(),
             }).ToList();
            classf.Insert(0, new SelectListItem()
            {
                Text = "---Selecionar---",
                Value = string.Empty.ToString(),
            });
            ViewData["Classificacao"] = classf;

            var compraV = Enum.GetValues(typeof(CompraVenda))
                .Cast<CompraVenda>()
                .Select(c => new SelectListItem
                {
                    Text = c.ToString(),
                    Value = ((int)c).ToString()
                }).ToList();
            compraV.Insert(0, new SelectListItem()
            {
                Text = "---Selecionar---",
                Value = string.Empty.ToString(),
            });
            ViewData["CompraVenda"] = compraV;

            var parceria = await _parceriaService.ObterPorIdAsync(id);
            return View(parceria);
        }
        //[ClaimsAuthorizeAttribute(ClaimTypes.InicioParceria, "Atualizar")]
        [HttpPost]
        public async Task<ActionResult> Atualizar(AtualizarInicioParceriaRequest parceriaRequest)
        {
            var parceria = AtualizarInicioParceriaRequest.ConverterParaEntidade(parceriaRequest);
            await _parceriaService.AtualizarAsync(parceria);
            return RedirectToAction("ObterTodos");
        }
        //[ClaimsAuthorizeAttribute(ClaimTypes.InicioParceria, "Excluir")]
        public async Task<ActionResult> Excluir(Guid id)
        {
            await _parceriaService.RemoverPorIdAsync(id);
            return RedirectToAction("ObterTodos");
        }
    }
}

BVS/Views/InicioParcerias/ObterPorId.cshtml
@model BVS.Models.Entity.Parceria.InicioParceria

@{
    ViewData["Title"] = "ObterPorId";
}
<div class="d-flex justify-content-between align-content-center pt-3 pb-2">
    <h1>Detalhes da Parceria</h1>
    <a class="btn btn-primary btn-lg" asp-action="ObterTodos">Voltar</a>
</div>

<div>
    <div class="card">
        <div class="card-header">Parceria e Associado</div>
        <div class="card-body row">
            <div class="col-md">
                <div class="form-group">
                    <label class="control-label">@Html.DisplayNameFor(model => model.Comprador)</label>
                    <input disabled class="form-control" value="@Html.DisplayFor(model => model.Comprador.Nome)"/>
                </div>
            </div>
            <div class="col-md">
                <div class="form-group">
                    <label class="control-label">@Html.DisplayNameFor(model => model.Associado)</label>
                    <input disabled class="form-control" value="@Html.DisplayFor(model => model.Associado.Nome)"/>
                </div>
            </div>
                    
        </div>
    </div>
    <div class="card">
        <div class="card-header">Dados do Início da Parceria</div>
        <div class="card-body row">
            <div class="col-md">
                <div class="form-group">
                <label class="control-label">@Html.DisplayNameFor(model => model.Lote)</label>
                <input disabled class="form-control" value="@Html.DisplayFor(model => model.Lote)"/>
                </div>
            </div>
            <div class="col-md">
                <div class="form-group">
                <label class="control-label">@Html.DisplayNameFor(model => model.PesoBruto)</label>
                <input disabled class="form-control" value="@Html.DisplayFor(model => model.PesoBruto)"/>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body row">
            <div class="col-md">
                <div class="form-group">
                    <label class="control-label">@Html.DisplayNameFor(model => model.RendimentoCarcaca)</label>
                    <input disabled class="form-control" value="@Html.DisplayFor(model => model.RendimentoCarcaca)"/>
                </div>                
                <div class="form-group">
                    <label class="control-label">@Html.DisplayNameFor(model => model.Arroba)</label>
                    <input disabled class="form-control" value="@Html.DisplayFor(model => model.Arroba)"/>
                </div>
            </div>
            <div class="col-md">
                <div class="form-group">
                <label class="control-label">@Html.DisplayNameFor(model => model.Classificacao)</label>
                <input disabled class="form-control" value="@Html.DisplayFor(model => model.Classificacao)"/>
                </div>
                <div class="form-group">
                <label class="control-label">@Html.DisplayNameFor(model => model.CompraVenda)</label>
                <input disabled class="form-control" value="@Html.DisplayFor(model => model.CompraVenda)"/>
                </div>
            </div> 
            <div class="col-md">
               <div class="form-group">
                <label class="control-label">@Html.DisplayNameFor(model => model.Quantidade)</label>
                <input disabled class="form-control" value="@Html.DisplayFor(model => model.Quantidade)"/>
                </div>
                        
                <div id="date" class="form-group">
                <label class="control-label">@Html.DisplayNameFor(model => model.DataInicioParceria)</label>
                <input disabled class="form-control" value="@String.Format("{0:dd/MM/yyyy}", Model.DataInicioParceria)"/>
                </div>
            </div>
            <div class="col-md">
                <div class="form-group">
                <label class="control-label">@Html.DisplayNameFor(model => model.Origem)</label>
                <input disabled class="form-control" value="@Html.DisplayFor(model => model.Origem)"/>
                </div>
                <div class="form-group">
                <label class="control-label">@Html.DisplayNameFor(model => model.Valor)</label>
                <input disabled class="form-control" value="@Html.DisplayFor(model => model.Valor)"/>
                </div>
            </div>

        </div>
    </div>    
</div>
<br />
<div> @*m-1  "@(new SelectList(ViewBag.selectAssociado, "Value", "Text"))"   @Html.DisplayFor(model => model.DataInicioParceria)*@
    <a class="btn btn-success btn-lg" asp-action="Atualizar" asp-route-id="@Model?.BoiId">Atualizar</a>    
</div>

BVS/Views/InicioParcerias/ObterTodos.cshtml
@model IEnumerable<BVS.Models.Entity.Parceria.InicioParceria>

@{
    ViewData["Title"] = "ObterTodos";
}
<div class="d-flex justify-content-between align-content-center pt-3 pb-2">
    <h1>Parcerias Cadastradas</h1>
    <a class="btn btn-primary btn-lg" asp-action="Inserir">Nova Parceria</a>
</div>
<br />
<div class="card">
    <div class="card-header">Dados Pessoais</div>
    <div class="card-body">        
        <table id="myTable" class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Lote)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.PesoBruto)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.RendimentoCarcaca)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Arroba)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Comprador)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Associado)
                        </th>
                        @*<th>
                            @Html.DisplayNameFor(model => model.Quantidade)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Classificacao)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.CompraVenda)
                        </th>*@
                        <th>
                            @Html.DisplayNameFor(model => model.DataInicioParceria)
                        </th>
                        @*<th>
                            @Html.DisplayNameFor(model => model.Origem)
                        </th>*@
                        <th>
                            @Html.DisplayNameFor(model => model.Valor)
                        </th>
                        <th></th>
                    </tr>
                </thead>
            <tbody>
                @foreach (var item in Model) {            
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Lote)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PesoBruto)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.RendimentoCarcaca)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Arroba)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Comprador.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Associado.Nome)
                        </td>
                        @*<td>
                            @Html.DisplayFor(modelItem => item.Quantidade)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Classificacao)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CompraVenda)
                        </td>*@
                        <td>
                            @Html.DisplayFor(modelItem => item.DataInicioParceria)
                        </td>
                        @*<td>
                            @Html.DisplayFor(modelItem => item.Origem)
                        </td>*@
                        <td>
                            @Html.DisplayFor(modelItem => item.Valor)
                        </td>
                        <td>
                            
                                    <a asp-action="Atualizar" class="btn btn-success m-1 btn-sm" asp-route-id="@item.BoiId">Atualizar</a> 
                                    <a asp-action="ObterPorId" class="btn btn-info m-1 btn-sm" asp-route-id="@item.BoiId">Detalhes</a> 
                   
                                    <button type="button" class="btn btn-warning m-1 btn-sm" data-toggle="modal" data-target="#saidaModal-@item.BoiId">
                                                Saida
                                    </button> 

                                    <button type="button" class="btn btn-danger m-1 btn-sm" data-toggle="modal" data-target="#deleteModal-@item.BoiId">
                                                Excluir
                                    </button>
                                <div class="modal fade" id="deleteModal-@item.BoiId" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="deleteModalLabel">Excluir Cliente</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Deseja realmente excluir a parceria entre @item.Comprador.Nome e @item.Associado.Nome?
                                            </div>
                                                <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Não</button>
                                                <a asp-action="Excluir" class="btn btn-danger m-1" asp-route-id="@item.BoiId">Delete</a>
                                                </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal fade" id="saidaModal-@item.BoiId" tabindex="-1" role="dialog" aria-labelledby="saidaModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="saidaModalLabel">Adicionar informação da Saida</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                            </div>
                                            <div class="modal-body">
                                            O que deseja verificar ?
                                            </div>
                                            <div class="modal-footer">
                                            <a asp-action="Inserir" class="btn btn-warning m-1 btn-sm" asp-route-id="@item.BoiId" asp-controller="AlteracaoSaidas">Saida</a>
                                            <a asp-action="Atualizar" class="btn btn-success m-1 btn-sm" asp-route-id="@item.BoiId" asp-controller="AlteracaoSaidas">Editar</a> 
                                            <a asp-action="ObterPorId" class="btn btn-info m-1 btn-sm" asp-route-id="@item.BoiId" asp-controller="AlteracaoSaidas">Detalhes</a>                             
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </td>                
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function(){
            $('#myTable').DataTable(
                {
                    "language":
                        {
                            "url":"//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese-Brasil.json" 
                        }
                });
        });
    </script>
}